# coding: utf-8

"""
    NetHSM

    All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class DecryptMode(str, Enum):
    """
    DecryptMode
    """

    """
    allowed enum values
    """
    RAW = 'RAW'
    PKCS1 = 'PKCS1'
    OAEP_MD5 = 'OAEP_MD5'
    OAEP_SHA1 = 'OAEP_SHA1'
    OAEP_SHA224 = 'OAEP_SHA224'
    OAEP_SHA256 = 'OAEP_SHA256'
    OAEP_SHA384 = 'OAEP_SHA384'
    OAEP_SHA512 = 'OAEP_SHA512'
    AES_CBC = 'AES_CBC'

    @classmethod
    def from_json(cls, json_str: str) -> DecryptMode:
        """Create an instance of DecryptMode from a JSON string"""
        return DecryptMode(json.loads(json_str))


