# coding: utf-8

"""
    NetHSM

    All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class EncryptMode(str, Enum):
    """
    EncryptMode
    """

    """
    allowed enum values
    """
    AES_CBC = 'AES_CBC'

    @classmethod
    def from_json(cls, json_str: str) -> EncryptMode:
        """Create an instance of EncryptMode from a JSON string"""
        return EncryptMode(json.loads(json_str))


