# coding: utf-8

"""
    NetHSM

    All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class KeyMechanism(str, Enum):
    """
    KeyMechanism
    """

    """
    allowed enum values
    """
    RSA_DECRYPTION_RAW = 'RSA_Decryption_RAW'
    RSA_DECRYPTION_PKCS1 = 'RSA_Decryption_PKCS1'
    RSA_DECRYPTION_OAEP_MD5 = 'RSA_Decryption_OAEP_MD5'
    RSA_DECRYPTION_OAEP_SHA1 = 'RSA_Decryption_OAEP_SHA1'
    RSA_DECRYPTION_OAEP_SHA224 = 'RSA_Decryption_OAEP_SHA224'
    RSA_DECRYPTION_OAEP_SHA256 = 'RSA_Decryption_OAEP_SHA256'
    RSA_DECRYPTION_OAEP_SHA384 = 'RSA_Decryption_OAEP_SHA384'
    RSA_DECRYPTION_OAEP_SHA512 = 'RSA_Decryption_OAEP_SHA512'
    RSA_SIGNATURE_PKCS1 = 'RSA_Signature_PKCS1'
    RSA_SIGNATURE_PSS_MD5 = 'RSA_Signature_PSS_MD5'
    RSA_SIGNATURE_PSS_SHA1 = 'RSA_Signature_PSS_SHA1'
    RSA_SIGNATURE_PSS_SHA224 = 'RSA_Signature_PSS_SHA224'
    RSA_SIGNATURE_PSS_SHA256 = 'RSA_Signature_PSS_SHA256'
    RSA_SIGNATURE_PSS_SHA384 = 'RSA_Signature_PSS_SHA384'
    RSA_SIGNATURE_PSS_SHA512 = 'RSA_Signature_PSS_SHA512'
    ED_DSA_SIGNATURE = 'EdDSA_Signature'
    ECDSA_SIGNATURE = 'ECDSA_Signature'
    AES_ENCRYPTION_CBC = 'AES_Encryption_CBC'
    AES_DECRYPTION_CBC = 'AES_Decryption_CBC'

    @classmethod
    def from_json(cls, json_str: str) -> KeyMechanism:
        """Create an instance of KeyMechanism from a JSON string"""
        return KeyMechanism(json.loads(json_str))


