# coding: utf-8

"""
    NetHSM

    All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class SignMode(str, Enum):
    """
    SignMode
    """

    """
    allowed enum values
    """
    PKCS1 = 'PKCS1'
    PSS_MD5 = 'PSS_MD5'
    PSS_SHA1 = 'PSS_SHA1'
    PSS_SHA224 = 'PSS_SHA224'
    PSS_SHA256 = 'PSS_SHA256'
    PSS_SHA384 = 'PSS_SHA384'
    PSS_SHA512 = 'PSS_SHA512'
    EDDSA = 'EdDSA'
    ECDSA = 'ECDSA'

    @classmethod
    def from_json(cls, json_str: str) -> SignMode:
        """Create an instance of SignMode from a JSON string"""
        return SignMode(json.loads(json_str))


