version: 2.1

orbs:
  win: circleci/windows@2.2.0
  python: circleci/python@0.2.1

jobs:
  build-msi-win:
    executor: win/default
    steps:
      - checkout
      - run: pip install -r ci-requirements.txt
      - run: python win_setup.py bdist_msi

  build-linux:
    executor: python/default
    steps:
      - checkout
      - run: make init
      - run: make CI

  install-test-pip:
    executor: python/default
    steps:
      - checkout
      - run: make system-pip-install
      - run: make system-nitropy-test-simple
      - run: make system-pip-uninstall
      - run: make system-pip-install
      - run: make system-nitropy-test-simple
      - run: make system-pip-install
      - run: make system-nitropy-test-simple
      - run: make system-pip-uninstall

  install-with-older-fido:
    executor: python/default
    steps:
      - checkout
      - run: python -m pip install fido2==0.7.2
      - run: make system-pip-install
      - run: make system-nitropy-test-simple

  install-last-version-and-no-upgrade-install:
    executor: python/default
    steps:
      - checkout
      - run: make system-pip-install-last-version
      - run: make system-nitropy-test-simple
      - run: make system-pip-install
      - run: make system-nitropy-test-simple
  
  install-last-version-uninstall-no-upgrade-install:
    executor: python/default
    steps:
      - checkout
      - run: make system-pip-install-last-version
      - run: make system-nitropy-test-simple
      - run: make system-pip-uninstall
      - run: make system-pip-install
      - run: make system-nitropy-test-simple
  
  install-last-version-upgrade-install:
    executor: python/default
    steps:
      - checkout
      - run: make system-pip-install-last-version
      - run: make system-nitropy-test-simple
      - run: make system-pip-install-upgrade
      - run: make system-nitropy-test-simple

workflows:
  main:
    jobs:
      - build-msi-win
      - build-linux
      - install-test-pip
      - install-with-older-fido
      - install-last-version-upgrade-install
      - install-last-version-uninstall-no-upgrade-install
      - install-last-version-and-no-upgrade-install
