version: 2.1

orbs:
  win: circleci/windows@2.2.0
  python: circleci/python@0.2.1

jobs:
  build-msi-win:
    executor: win/default
    steps:
      - checkout
      - run: pip install -r dev-requirements.txt
      - run: python win_setup.py bdist_msi

  build-linux:
    executor: python/default
    steps:
      - checkout
      - run: make init
      - run: make CI

workflows:
  main:
    jobs:
      - build-msi-win
      - build-linux
