# coding: utf-8

"""
    NetHSM

    All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

from pynitrokey.nethsm.client.paths.config_backup_passphrase.put import ConfigBackupPassphrasePut
from pynitrokey.nethsm.client.paths.config_logging.get import ConfigLoggingGet
from pynitrokey.nethsm.client.paths.config_logging.put import ConfigLoggingPut
from pynitrokey.nethsm.client.paths.config_network.get import ConfigNetworkGet
from pynitrokey.nethsm.client.paths.config_network.put import ConfigNetworkPut
from pynitrokey.nethsm.client.paths.config_time.get import ConfigTimeGet
from pynitrokey.nethsm.client.paths.config_time.put import ConfigTimePut
from pynitrokey.nethsm.client.paths.config_tls_cert_pem.get import ConfigTlsCertPemGet
from pynitrokey.nethsm.client.paths.config_tls_cert_pem.put import ConfigTlsCertPemPut
from pynitrokey.nethsm.client.paths.config_tls_csr_pem.post import ConfigTlsCsrPemPost
from pynitrokey.nethsm.client.paths.config_tls_generate.post import ConfigTlsGeneratePost
from pynitrokey.nethsm.client.paths.config_tls_public_pem.get import ConfigTlsPublicPemGet
from pynitrokey.nethsm.client.paths.config_unattended_boot.get import ConfigUnattendedBootGet
from pynitrokey.nethsm.client.paths.config_unattended_boot.put import ConfigUnattendedBootPut
from pynitrokey.nethsm.client.paths.config_unlock_passphrase.put import ConfigUnlockPassphrasePut
from pynitrokey.nethsm.client.paths.health_alive.get import HealthAliveGet
from pynitrokey.nethsm.client.paths.health_ready.get import HealthReadyGet
from pynitrokey.nethsm.client.paths.health_state.get import HealthStateGet
from pynitrokey.nethsm.client.paths.info.get import InfoGet
from pynitrokey.nethsm.client.paths.keys_generate.post import KeysGeneratePost
from pynitrokey.nethsm.client.paths.keys.get import KeysGet
from pynitrokey.nethsm.client.paths.keys_key_id_cert.delete import KeysKeyIdCertDelete
from pynitrokey.nethsm.client.paths.keys_key_id_cert.get import KeysKeyIdCertGet
from pynitrokey.nethsm.client.paths.keys_key_id_cert.put import KeysKeyIdCertPut
from pynitrokey.nethsm.client.paths.keys_key_id_csr_pem.post import KeysKeyIdCsrPemPost
from pynitrokey.nethsm.client.paths.keys_key_id_decrypt.post import KeysKeyIdDecryptPost
from pynitrokey.nethsm.client.paths.keys_key_id.delete import KeysKeyIdDelete
from pynitrokey.nethsm.client.paths.keys_key_id_encrypt.post import KeysKeyIdEncryptPost
from pynitrokey.nethsm.client.paths.keys_key_id.get import KeysKeyIdGet
from pynitrokey.nethsm.client.paths.keys_key_id_public_pem.get import KeysKeyIdPublicPemGet
from pynitrokey.nethsm.client.paths.keys_key_id.put import KeysKeyIdPut
from pynitrokey.nethsm.client.paths.keys_key_id_restrictions_tags_tag.delete import KeysKeyIdRestrictionsTagsTagDelete
from pynitrokey.nethsm.client.paths.keys_key_id_restrictions_tags_tag.put import KeysKeyIdRestrictionsTagsTagPut
from pynitrokey.nethsm.client.paths.keys_key_id_sign.post import KeysKeyIdSignPost
from pynitrokey.nethsm.client.paths.keys.post import KeysPost
from pynitrokey.nethsm.client.paths.lock.post import LockPost
from pynitrokey.nethsm.client.paths.metrics.get import MetricsGet
from pynitrokey.nethsm.client.paths.provision.post import ProvisionPost
from pynitrokey.nethsm.client.paths.random.post import RandomPost
from pynitrokey.nethsm.client.paths.system_backup.post import SystemBackupPost
from pynitrokey.nethsm.client.paths.system_cancel_update.post import SystemCancelUpdatePost
from pynitrokey.nethsm.client.paths.system_commit_update.post import SystemCommitUpdatePost
from pynitrokey.nethsm.client.paths.system_factory_reset.post import SystemFactoryResetPost
from pynitrokey.nethsm.client.paths.system_info.get import SystemInfoGet
from pynitrokey.nethsm.client.paths.system_reboot.post import SystemRebootPost
from pynitrokey.nethsm.client.paths.system_restore.post import SystemRestorePost
from pynitrokey.nethsm.client.paths.system_shutdown.post import SystemShutdownPost
from pynitrokey.nethsm.client.paths.system_update.post import SystemUpdatePost
from pynitrokey.nethsm.client.paths.unlock.post import UnlockPost
from pynitrokey.nethsm.client.paths.users.get import UsersGet
from pynitrokey.nethsm.client.paths.users.post import UsersPost
from pynitrokey.nethsm.client.paths.users_user_id.delete import UsersUserIdDelete
from pynitrokey.nethsm.client.paths.users_user_id.get import UsersUserIdGet
from pynitrokey.nethsm.client.paths.users_user_id_passphrase.post import UsersUserIdPassphrasePost
from pynitrokey.nethsm.client.paths.users_user_id.put import UsersUserIdPut
from pynitrokey.nethsm.client.paths.users_user_id_tags.get import UsersUserIdTagsGet
from pynitrokey.nethsm.client.paths.users_user_id_tags_tag.delete import UsersUserIdTagsTagDelete
from pynitrokey.nethsm.client.paths.users_user_id_tags_tag.put import UsersUserIdTagsTagPut


class DefaultApi(
    ConfigBackupPassphrasePut,
    ConfigLoggingGet,
    ConfigLoggingPut,
    ConfigNetworkGet,
    ConfigNetworkPut,
    ConfigTimeGet,
    ConfigTimePut,
    ConfigTlsCertPemGet,
    ConfigTlsCertPemPut,
    ConfigTlsCsrPemPost,
    ConfigTlsGeneratePost,
    ConfigTlsPublicPemGet,
    ConfigUnattendedBootGet,
    ConfigUnattendedBootPut,
    ConfigUnlockPassphrasePut,
    HealthAliveGet,
    HealthReadyGet,
    HealthStateGet,
    InfoGet,
    KeysGeneratePost,
    KeysGet,
    KeysKeyIdCertDelete,
    KeysKeyIdCertGet,
    KeysKeyIdCertPut,
    KeysKeyIdCsrPemPost,
    KeysKeyIdDecryptPost,
    KeysKeyIdDelete,
    KeysKeyIdEncryptPost,
    KeysKeyIdGet,
    KeysKeyIdPublicPemGet,
    KeysKeyIdPut,
    KeysKeyIdRestrictionsTagsTagDelete,
    KeysKeyIdRestrictionsTagsTagPut,
    KeysKeyIdSignPost,
    KeysPost,
    LockPost,
    MetricsGet,
    ProvisionPost,
    RandomPost,
    SystemBackupPost,
    SystemCancelUpdatePost,
    SystemCommitUpdatePost,
    SystemFactoryResetPost,
    SystemInfoGet,
    SystemRebootPost,
    SystemRestorePost,
    SystemShutdownPost,
    SystemUpdatePost,
    UnlockPost,
    UsersGet,
    UsersPost,
    UsersUserIdDelete,
    UsersUserIdGet,
    UsersUserIdPassphrasePost,
    UsersUserIdPut,
    UsersUserIdTagsGet,
    UsersUserIdTagsTagDelete,
    UsersUserIdTagsTagPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
