# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.config_backup_passphrase.put.operation import ApiForPut


class ConfigBackupPassphrase(
    ApiForPut,
):
    pass
