# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.config_logging.get.operation import ApiForGet
from pynitrokey.nethsm.client.paths.config_logging.put.operation import ApiForPut


class ConfigLogging(
    ApiForGet,
    ApiForPut,
):
    pass
