# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.config_unattended_boot.get.operation import ApiForGet
from pynitrokey.nethsm.client.paths.config_unattended_boot.put.operation import ApiForPut


class ConfigUnattendedBoot(
    ApiForGet,
    ApiForPut,
):
    pass
