# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.config_tls_cert_pem.get.operation import ApiForGet
from pynitrokey.nethsm.client.paths.config_tls_cert_pem.put.operation import ApiForPut


class ConfigTlsCertPem(
    ApiForGet,
    ApiForPut,
):
    pass
