# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.config_time.get.operation import ApiForGet
from pynitrokey.nethsm.client.paths.config_time.put.operation import ApiForPut


class ConfigTime(
    ApiForGet,
    ApiForPut,
):
    pass
