# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.health_ready.get.operation import ApiForGet


class HealthReady(
    ApiForGet,
):
    pass
