# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.keys_key_id_decrypt.post.operation import ApiForPost


class KeysKeyIDDecrypt(
    ApiForPost,
):
    pass
