# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.keys_key_id_public_pem.get.operation import ApiForGet


class KeysKeyIDPublicPem(
    ApiForGet,
):
    pass
