# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.keys_key_id.delete.operation import ApiForDelete
from pynitrokey.nethsm.client.paths.keys_key_id.get.operation import ApiForGet
from pynitrokey.nethsm.client.paths.keys_key_id.put.operation import ApiForPut


class KeysKeyID(
    ApiForDelete,
    ApiForGet,
    ApiForPut,
):
    pass
