# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.keys_key_id_cert.delete.operation import ApiForDelete
from pynitrokey.nethsm.client.paths.keys_key_id_cert.get.operation import ApiForGet
from pynitrokey.nethsm.client.paths.keys_key_id_cert.put.operation import ApiForPut


class KeysKeyIDCert(
    ApiForDelete,
    ApiForGet,
    ApiForPut,
):
    pass
