# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.keys.get.operation import ApiForGet
from pynitrokey.nethsm.client.paths.keys.post.operation import ApiForPost


class Keys(
    ApiForGet,
    ApiForPost,
):
    pass
