# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.metrics.get.operation import ApiForGet


class Metrics(
    ApiForGet,
):
    pass
