# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.provision.post.operation import ApiForPost


class Provision(
    ApiForPost,
):
    pass
