# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.system_reboot.post.operation import ApiForPost


class SystemReboot(
    ApiForPost,
):
    pass
