# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.system_restore.post.operation import ApiForPost


class SystemRestore(
    ApiForPost,
):
    pass
