# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.system_factory_reset.post.operation import ApiForPost


class SystemFactoryReset(
    ApiForPost,
):
    pass
