# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.users_user_id_tags.get.operation import ApiForGet


class UsersUserIDTags(
    ApiForGet,
):
    pass
