# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from pynitrokey.nethsm.client.paths.users.get.operation import ApiForGet
from pynitrokey.nethsm.client.paths.users.post.operation import ApiForPost


class Users(
    ApiForGet,
    ApiForPost,
):
    pass
