# Copyright Nitrokey GmbH
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: Continuous delivery - PyPI

on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

env:
  POETRY_SPEC: poetry >=2,<3

jobs:
  check-version-tag:
    name: Check version tag
    runs-on: ubuntu-latest
    container: python:3.11-slim
    if: github.event_name == 'release'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dependencies
        run: pip install toml-cli
      - name: Check version tag
        shell: bash
        run: |
          PYPROJECT_VERSION="v$(toml get --toml-path pyproject.toml project.version)"
          TAG_VERSION="${{ github.event.release.tag_name }}"
          if [[ $PYPROJECT_VERSION == $TAG_VERSION ]]; then exit 0; else exit 1; fi
  build:
    name: Build
    runs-on: ubuntu-latest
    container: python:3.11-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install required packages
        run: |
          apt update
          apt install -y binutils gcc libpcsclite-dev libusb-1.0-0 make swig
      - name: Install poetry
        run: pip install "${POETRY_SPEC}"
      - name: Build
        run: poetry build
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: nitropy-pypi
          path: dist
  publish-testpypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' || github.ref == 'refs/heads/main'
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pynitrokey
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: nitropy-pypi
          path: dist
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build, check-version-tag]
    if: github.event_name == 'release'
    environment:
      name: pypi
      url: https://pypi.org/p/pynitrokey
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: nitropy-pypi
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
